services:
    minio:
        ports:
            - 9000:9000
            - 9001:9001
        user: 1000:1000
        container_name: minio1_docker
        environment:
            - AWS_SDK_JS_SUPPRESS_MAINTENANCE_MODE_MESSAGE=1
            - MINIO_ROOT_USER=ROOTUSER
            - MINIO_ROOT_PASSWORD=CHANGEME123
        volumes:
          - ./minio/data:/data
        image: quay.io/minio/minio
        command: server /data --console-address ":9001"
        
    ollama:
        image: ollama/ollama:latest
        volumes:
          - ./ollama/ollama:/root/.ollama
          - ./startup.sh:/startup.sh
        container_name: ollama_docker
        pull_policy: always
        tty: true
        restart: unless-stopped
        ports:
          - 11434:11434
        deploy: 
          resources:
            reservations:
             devices:
               - driver: nvidia
                 count: 1
                 capabilities: [gpu]

    chroma:
        image: chromadb/chroma
        volumes:
          - ./chroma/chroma:/root/.chroma
        container_name: chroma_docker
        restart: unless-stopped
        ports:
          - 8000:8000
        environment:
          - CHROMA_SERVER_CORS_ALLOW_ORIGIN='["*"]'

    postgres:
        image: postgres:latest
        container_name: postgres_docker
        restart: unless-stopped
        environment:
          POSTGRES_PASSWORD: postgres
        volumes:
          - ./postgres/ pgdata:/var/lib/postgresql/data