name: Glossify

on: 
  workflow_dispatch:
    inputs:
      directory-sorgente:
        description: 'Directory file sorgente'
        required: true
      directory-glossario:
        description: 'Directory files glossario'
        required: true

jobs:
  glossify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
  
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
  
      - name: Run gloss.py
        run: python actions/gloss.py ${{ inputs.directory-sorgente }}
        env:
          GLOSSARIO_PATH: ${{ inputs.directory-glossario }}
          CURRENT_DIRECTORY: ${{ inputs.directory-sorgente }}

      - name: Commit and push changes
        run: | 
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add '*.tex'
          git commit -m "Glossified .tex"
          git push origin HEAD:${{ github.ref }}
        working-directory: ${{ inputs.directory-sorgente }}
